# Generated by Django 6.0 on 2026-01-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='video-thumbnails'),
        ),
    ]
