# Generated by Django 6.0 on 2026-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_videolog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='videourl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
