# Generated by Django 6.0 on 2026-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_videolog_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='useUrl',
            field=models.BooleanField(default=False),
        ),
    ]
