# Generated by Django 6.0 on 2026-01-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_videolog_useurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
